package com.github.dirtpowered.betatorelease.proxy.translator.registry.b18;

import com.github.dirtpowered.betaprotocollib.BetaLib;
import com.github.dirtpowered.betaprotocollib.data.version.MinecraftVersion;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.AnimationPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.BlockDigPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.BlockItemSwitchPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.BlockPlacePacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.ChatPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.CloseWindowPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.EntityActionPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.FlyingPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.HandshakePacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.KeepAlivePacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.KickDisconnectPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.PlayerLookMovePacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.PlayerLookPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.PlayerPositionPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.TransactionPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.UpdateHealthPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.UpdateSignPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.UseEntityPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_7.data.WindowClickPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_8.data.CreativeItemGetPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_8.data.LoginPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_8.data.RespawnPacketData;
import com.github.dirtpowered.betaprotocollib.packet.Version_B1_8.data.ServerListPingPacketData;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.LoginDisconnectTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerBlockChangeTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerBlockValueTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerChatTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerChunkDataTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerCloseWindowTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerConfirmTransactionTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerDisconnectTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityAnimationTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityCollectItemTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityDestroyTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityEquipmentTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityHeadLookTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityMetadataTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityPositionRotationTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityPositionTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityRotationTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntitySetPassengersTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityStatusTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityTeleportTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerEntityVelocityTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerExplosionTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerMapDataTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerMultiBlockChangeTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerOpenWindowTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayBuiltinSoundTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayEffectTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayerChangeHeldItemTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayerListEntryTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayerPositionRotationTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerPlayerUseBedTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSetSlotTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnGlobalEntityTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnMobTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnObjectTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnPaintingTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnPlayerTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerSpawnPositionTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerUnloadChunkTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerUpdateTileEntityTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerVehicleMoveTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerWindowItemsTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.ServerWindowPropertyTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b17.UpdateTimeTranslator;
import com.github.dirtpowered.betatorelease.proxy.translator.clientbound.b18.*;
import com.github.dirtpowered.betatorelease.proxy.translator.registry.BetaToModernRegistry;
import com.github.dirtpowered.betatorelease.proxy.translator.registry.ModernToBetaRegistry;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.AnimationPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.BlockDigPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.BlockItemSwitchPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.BlockPlacePacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.ChatPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.CloseWindowPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.EntityActionPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.FlyingPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.HandshakePacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.KeepAlivePacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.KickDisconnectPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.PlayerLookMovePacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.PlayerLookPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.PlayerPositionPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.TransactionPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.UpdateHealthPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.UpdateSignPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.UseEntityPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b17.WindowClickPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b18.CreativeItemGetPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b18.LoginPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b18.RespawnPacketHandler;
import com.github.dirtpowered.betatorelease.proxy.translator.serverbound.b18.ServerListPingPacketHandler;
import com.github.steveice10.mc.protocol.packet.ingame.server.*;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.*;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.player.ServerPlayerChangeHeldItemPacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.player.ServerPlayerHealthPacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.player.ServerPlayerPositionRotationPacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.player.ServerPlayerUseBedPacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.entity.spawn.*;
import com.github.steveice10.mc.protocol.packet.ingame.server.window.*;
import com.github.steveice10.mc.protocol.packet.ingame.server.world.*;
import com.github.steveice10.mc.protocol.packet.login.server.LoginDisconnectPacket;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class B18Registry {
    private final BetaToModernRegistry betaToModernRegistry;
    private final ModernToBetaRegistry modernToBetaRegistry;

    public void register() {
        BetaLib.inject(MinecraftVersion.B_1_8_1);
        // 1.8
        betaToModernRegistry.registerTranslator(LoginPacketData.class, new LoginPacketHandler());
        betaToModernRegistry.registerTranslator(RespawnPacketData.class, new RespawnPacketHandler());
        betaToModernRegistry.registerTranslator(ServerListPingPacketData.class, new ServerListPingPacketHandler());
        betaToModernRegistry.registerTranslator(CreativeItemGetPacketData.class, new CreativeItemGetPacketHandler());

        betaToModernRegistry.registerTranslator(HandshakePacketData.class, new HandshakePacketHandler());
        betaToModernRegistry.registerTranslator(PlayerLookMovePacketData.class, new PlayerLookMovePacketHandler());
        betaToModernRegistry.registerTranslator(PlayerPositionPacketData.class, new PlayerPositionPacketHandler());
        betaToModernRegistry.registerTranslator(KeepAlivePacketData.class, new KeepAlivePacketHandler());
        betaToModernRegistry.registerTranslator(ChatPacketData.class, new ChatPacketHandler());
        betaToModernRegistry.registerTranslator(UpdateHealthPacketData.class, new UpdateHealthPacketHandler());
        betaToModernRegistry.registerTranslator(KickDisconnectPacketData.class, new KickDisconnectPacketHandler());
        betaToModernRegistry.registerTranslator(AnimationPacketData.class, new AnimationPacketHandler());
        betaToModernRegistry.registerTranslator(EntityActionPacketData.class, new EntityActionPacketHandler());
        betaToModernRegistry.registerTranslator(BlockItemSwitchPacketData.class, new BlockItemSwitchPacketHandler());
        betaToModernRegistry.registerTranslator(BlockDigPacketData.class, new BlockDigPacketHandler());
        betaToModernRegistry.registerTranslator(FlyingPacketData.class, new FlyingPacketHandler());
        betaToModernRegistry.registerTranslator(PlayerLookPacketData.class, new PlayerLookPacketHandler());
        betaToModernRegistry.registerTranslator(BlockPlacePacketData.class, new BlockPlacePacketHandler());
        betaToModernRegistry.registerTranslator(CloseWindowPacketData.class, new CloseWindowPacketHandler());
        betaToModernRegistry.registerTranslator(WindowClickPacketData.class, new WindowClickPacketHandler());
        betaToModernRegistry.registerTranslator(TransactionPacketData.class, new TransactionPacketHandler());
        betaToModernRegistry.registerTranslator(UseEntityPacketData.class, new UseEntityPacketHandler());
        betaToModernRegistry.registerTranslator(UpdateSignPacketData.class, new UpdateSignPacketHandler());

        // 1.8
        modernToBetaRegistry.registerTranslator(ServerRespawnPacket.class, new ServerRespawnTranslator());
        modernToBetaRegistry.registerTranslator(ServerJoinGamePacket.class, new ServerJoinGameTranslator());
        modernToBetaRegistry.registerTranslator(ServerKeepAlivePacket.class, new ServerKeepAliveTranslator());
        modernToBetaRegistry.registerTranslator(ServerNotifyClientPacket.class, new ServerNotifyClientTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayerHealthPacket.class, new ServerPlayerHealthTranslator());

        modernToBetaRegistry.registerTranslator(ServerChatPacket.class, new ServerChatTranslator());
        modernToBetaRegistry.registerTranslator(ServerUpdateTimePacket.class, new UpdateTimeTranslator());
        modernToBetaRegistry.registerTranslator(ServerChunkDataPacket.class, new ServerChunkDataTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnMobPacket.class, new ServerSpawnMobTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnPlayerPacket.class, new ServerSpawnPlayerTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayerPositionRotationPacket.class, new ServerPlayerPositionRotationTranslator());
        modernToBetaRegistry.registerTranslator(ServerBlockChangePacket.class, new ServerBlockChangeTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityHeadLookPacket.class, new ServerEntityHeadLookTranslator());
        modernToBetaRegistry.registerTranslator(ServerSetSlotPacket.class, new ServerSetSlotTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityVelocityPacket.class, new ServerEntityVelocityTranslator());
        modernToBetaRegistry.registerTranslator(ServerUnloadChunkPacket.class, new ServerUnloadChunkTranslator());
        modernToBetaRegistry.registerTranslator(ServerMultiBlockChangePacket.class, new ServerMultiBlockChangeTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnPositionPacket.class, new ServerSpawnPositionTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityTeleportPacket.class, new ServerEntityTeleportTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityPositionPacket.class, new ServerEntityPositionTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityDestroyPacket.class, new ServerEntityDestroyTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityAnimationPacket.class, new ServerEntityAnimationTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayerChangeHeldItemPacket.class, new ServerPlayerChangeHeldItemTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityPositionRotationPacket.class, new ServerEntityPositionRotationTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityRotationPacket.class, new ServerEntityRotationTranslator());
        modernToBetaRegistry.registerTranslator(LoginDisconnectPacket.class, new LoginDisconnectTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityStatusPacket.class, new ServerEntityStatusTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnGlobalEntityPacket.class, new ServerSpawnGlobalEntityTranslator());
        modernToBetaRegistry.registerTranslator(ServerExplosionPacket.class, new ServerExplosionTranslator());
        modernToBetaRegistry.registerTranslator(ServerOpenWindowPacket.class, new ServerOpenWindowTranslator());
        modernToBetaRegistry.registerTranslator(ServerWindowItemsPacket.class, new ServerWindowItemsTranslator());
        modernToBetaRegistry.registerTranslator(ServerConfirmTransactionPacket.class, new ServerConfirmTransactionTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnObjectPacket.class, new ServerSpawnObjectTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityCollectItemPacket.class, new ServerEntityCollectItemTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityMetadataPacket.class, new ServerEntityMetadataTranslator());
        modernToBetaRegistry.registerTranslator(ServerUpdateTileEntityPacket.class, new ServerUpdateTileEntityTranslator());
        modernToBetaRegistry.registerTranslator(ServerDisconnectPacket.class, new ServerDisconnectTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntityEquipmentPacket.class, new ServerEntityEquipmentTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayerListEntryPacket.class, new ServerPlayerListEntryTranslator());
        modernToBetaRegistry.registerTranslator(ServerEntitySetPassengersPacket.class, new ServerEntitySetPassengersTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayBuiltinSoundPacket.class, new ServerPlayBuiltinSoundTranslator());
        modernToBetaRegistry.registerTranslator(ServerVehicleMovePacket.class, new ServerVehicleMoveTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayerUseBedPacket.class, new ServerPlayerUseBedTranslator());
        modernToBetaRegistry.registerTranslator(ServerSpawnPaintingPacket.class, new ServerSpawnPaintingTranslator());
        modernToBetaRegistry.registerTranslator(ServerCloseWindowPacket.class, new ServerCloseWindowTranslator());
        modernToBetaRegistry.registerTranslator(ServerWindowPropertyPacket.class, new ServerWindowPropertyTranslator());
        modernToBetaRegistry.registerTranslator(ServerPlayEffectPacket.class, new ServerPlayEffectTranslator());
        modernToBetaRegistry.registerTranslator(ServerMapDataPacket.class, new ServerMapDataTranslator());
        modernToBetaRegistry.registerTranslator(ServerBlockValuePacket.class, new ServerBlockValueTranslator());
    }
}